# Site settings
title: dayDreams
email: ghoshbinayak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Explorations, experiences of Binayak Ghosh.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ghoshbinayak.github.io" # the base hostname & protocol for your site
twitter_username: binayak_ghosh
github_username:  ghoshbinayak

# Build settings
markdown: kramdown
safe: true
exclude: ['README.md', 'dayDreams.sublime-project']